In [58]:
#Load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier, export_graphviz



In [59]:
#Load data from url
url = "https://raw.githubusercontent.com/callxpert/datasets/master/Loan-applicant-details.csv"
names = ['Loan_ID','Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Property_Area','Loan_Status']
dataset = pd.read_csv(url, names=names)
dataset

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001003    Male     Yes          1      Graduate            No   
1    LP001005    Male     Yes          0      Graduate           Yes   
2    LP001006    Male     Yes          0  Not Graduate            No   
3    LP001008    Male      No          0      Graduate            No   
4    LP001011    Male     Yes          2      Graduate           Yes   
..        ...     ...     ...        ...           ...           ...   
475  LP002978  Female      No          0      Graduate            No   
476  LP002979    Male     Yes         3+      Graduate            No   
477  LP002983    Male     Yes          1      Graduate            No   
478  LP002984    Male     Yes          2      Graduate            No   
479  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               4583             1508.0         128               360   
1               3000                0.0          66               360   
2               2583             2358.0         120               360   
3               6000                0.0         141               360   
4               5417             4196.0         267               360   
..               ...                ...         ...               ...   
475             2900                0.0          71               360   
476             4106                0.0          40               180   
477             8072              240.0         253               360   
478             7583                0.0         187               360   
479             4583                0.0         133               360   

     Credit_History Property_Area Loan_Status  
0                 1         Rural           N  
1                 1         Urban           Y  
2                 1         Urban           Y  
3                 1         Urban           Y  
4                 1         Urban           Y  
..              ...           ...         ...  
475               1         Rural           Y  
476               1         Rural           Y  
477               1         Urban           Y  
478               1         Urban           Y  
479               0     Semiurban           N  

[480 rows x 13 columns]

In [60]:
dataset.head(20)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0   LP001003    Male     Yes          1      Graduate            No   
1   LP001005    Male     Yes          0      Graduate           Yes   
2   LP001006    Male     Yes          0  Not Graduate            No   
3   LP001008    Male      No          0      Graduate            No   
4   LP001011    Male     Yes          2      Graduate           Yes   
5   LP001013    Male     Yes          0  Not Graduate            No   
6   LP001014    Male     Yes         3+      Graduate            No   
7   LP001018    Male     Yes          2      Graduate            No   
8   LP001020    Male     Yes          1      Graduate            No   
9   LP001024    Male     Yes          2      Graduate            No   
10  LP001028    Male     Yes          2      Graduate            No   
11  LP001029    Male      No          0      Graduate            No   
12  LP001030    Male     Yes          2      Graduate            No   
13  LP001032    Male      No          0      Graduate            No   
14  LP001036  Female      No          0      Graduate            No   
15  LP001038    Male     Yes          0  Not Graduate            No   
16  LP001043    Male     Yes          0  Not Graduate            No   
17  LP001046    Male     Yes          1      Graduate            No   
18  LP001047    Male     Yes          0  Not Graduate            No   
19  LP001066    Male     Yes          0      Graduate           Yes   

    ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              4583             1508.0         128               360   
1              3000                0.0          66               360   
2              2583             2358.0         120               360   
3              6000                0.0         141               360   
4              5417             4196.0         267               360   
5              2333             1516.0          95               360   
6              3036             2504.0         158               360   
7              4006             1526.0         168               360   
8             12841            10968.0         349               360   
9              3200              700.0          70               360   
10             3073             8106.0         200               360   
11             1853             2840.0         114               360   
12             1299             1086.0          17               120   
13             4950                0.0         125               360   
14             3510                0.0          76               360   
15             4887                0.0         133               360   
16             7660                0.0         104               360   
17             5955             5625.0         315               360   
18             2600             1911.0         116               360   
19             9560                0.0         191               360   

    Credit_History Property_Area Loan_Status  
0                1         Rural           N  
1                1         Urban           Y  
2                1         Urban           Y  
3                1         Urban           Y  
4                1         Urban           Y  
5                1         Urban           Y  
6                0     Semiurban           N  
7                1         Urban           Y  
8                1     Semiurban           N  
9                1         Urban           Y  
10               1         Urban           Y  
11               1         Rural           N  
12               1         Urban           Y  
13               1         Urban           Y  
14               0         Urban           N  
15               1         Rural           N  
16               0         Urban           N  
17               1         Urban           Y  
18               0     Semiurban           N  
19               1     Semiurban           Y

In [61]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['Gender','Married','Dependents','Education','Self_Employed','Property_Area','Loan_Status']
le = LabelEncoder()
for i in var_mod:
    dataset[i] = le.fit_transform(dataset[i])

In [62]:
dataset

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0    LP001003       1        1           1          0              0   
1    LP001005       1        1           0          0              1   
2    LP001006       1        1           0          1              0   
3    LP001008       1        0           0          0              0   
4    LP001011       1        1           2          0              1   
..        ...     ...      ...         ...        ...            ...   
475  LP002978       0        0           0          0              0   
476  LP002979       1        1           3          0              0   
477  LP002983       1        1           1          0              0   
478  LP002984       1        1           2          0              0   
479  LP002990       0        0           0          0              1   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               4583             1508.0         128               360   
1               3000                0.0          66               360   
2               2583             2358.0         120               360   
3               6000                0.0         141               360   
4               5417             4196.0         267               360   
..               ...                ...         ...               ...   
475             2900                0.0          71               360   
476             4106                0.0          40               180   
477             8072              240.0         253               360   
478             7583                0.0         187               360   
479             4583                0.0         133               360   

     Credit_History  Property_Area  Loan_Status  
0                 1              0            0  
1                 1              2            1  
2                 1              2            1  
3                 1              2            1  
4                 1              2            1  
..              ...            ...          ...  
475               1              0            1  
476               1              0            1  
477               1              2            1  
478               1              2            1  
479               0              1            0  

[480 rows x 13 columns]

In [63]:
array=dataset.values
array

array([['LP001003', 1, 1, ..., 1, 0, 0],
       ['LP001005', 1, 1, ..., 1, 2, 1],
       ['LP001006', 1, 1, ..., 1, 2, 1],
       ...,
       ['LP002983', 1, 1, ..., 1, 2, 1],
       ['LP002984', 1, 1, ..., 1, 2, 1],
       ['LP002990', 0, 0, ..., 0, 1, 0]], dtype=object)

In [64]:
X=array[:,6:11]
X

array([[4583, 1508.0, 128, 360, 1],
       [3000, 0.0, 66, 360, 1],
       [2583, 2358.0, 120, 360, 1],
       ...,
       [8072, 240.0, 253, 360, 1],
       [7583, 0.0, 187, 360, 1],
       [4583, 0.0, 133, 360, 0]], dtype=object)

In [65]:
Y = array[:,12]
Y=Y.astype('int')
Y

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,

In [66]:
test = array[:,6]
test

array([4583, 3000, 2583, 6000, 5417, 2333, 3036, 4006, 12841, 3200, 3073,
       1853, 1299, 4950, 3510, 4887, 7660, 5955, 2600, 9560, 2799, 4226,
       1442, 3167, 4692, 3500, 12500, 3667, 4166, 3748, 3600, 1800, 3941,
       5649, 5821, 2645, 4000, 1928, 3086, 4230, 4616, 11500, 2708, 2132,
       3366, 8080, 3357, 2500, 3029, 2609, 4166, 5726, 3200, 10750, 7100,
       4300, 3208, 1875, 3500, 5266, 3750, 3750, 1000, 3167, 3846, 1378,
       3988, 2366, 2500, 8566, 5695, 2958, 6250, 3273, 4133, 3620, 2484,
       1977, 4188, 1759, 4288, 4843, 3052, 11417, 3800, 2071, 5316, 14583,
       3167, 5568, 10408, 4166, 2137, 2957, 4300, 10513, 2014, 2718, 3459,
       4895, 4000, 4583, 3316, 14999, 4200, 5042, 5417, 6950, 2698, 11757,
       2330, 14866, 1538, 10000, 4860, 6277, 2577, 9166, 2281, 3254,
       39999, 9538, 4583, 1863, 7933, 3089, 4167, 9323, 4583, 2439, 2237,
       8000, 3522, 5708, 4344, 3497, 2045, 5516, 3750, 2333, 6400, 4600,
       33846, 3625, 39147, 2178, 9328, 4885,

In [67]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(X, Y, test_size=0.2, random_state=7)


In [68]:
x_train

array([[3522, 0.0, 81, 180, 1],
       [6000, 0.0, 141, 360, 1],
       [3333, 0.0, 70, 360, 1],
       ...,
       [3500, 1667.0, 114, 360, 1],
       [3427, 0.0, 138, 360, 1],
       [6250, 0.0, 128, 360, 1]], dtype=object)

In [69]:
y_train

array([0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,

In [70]:
# Decision tree : Decision tree is a type of supervised learning algorithm (having a pre-defined target variable) that is mostly used in classification problems. It works for both categorical and continuous input and output variables

model = DecisionTreeClassifier()
model.fit(x_train,y_train)
predictions = model.predict(x_test)
print(accuracy_score(y_test, predictions))



0.625


In [71]:
# Logistic Regression : Logistic Regression is a classification algorithm. It is used to predict a binary outcome (1 / 0, Yes / No, True / False) given a set of independent variables. To represent binary / categorical outcome, we use dummy variables
model = LogisticRegression()
model.fit(x_train,y_train)
predictions = model.predict(x_test)
print(accuracy_score(y_test, predictions))

0.7708333333333334


In [72]:
# Random forest : Random forests or random decision forests are an ensemble learning method for classification, regression and other tasks, that operate by constructing a multitude of decision trees at training time and outputting the class that is the mode of the classes (classification) or mean prediction (regression) of the individual trees
model = RandomForestClassifier(n_estimators=100)
model.fit(x_train,y_train)
predictions = model.predict(x_test)
print(accuracy_score(y_test, predictions))

0.7395833333333334
